# Generated by Django 4.2 on 2023-06-27 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.IntegerField(blank=True, default=0, null=True)),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('source_link', models.CharField(blank=True, max_length=512, null=True)),
                ('generated', models.BooleanField(default=False)),
                ('adult', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('original_title', models.CharField(blank=True, max_length=255, null=True)),
                ('runtime', models.IntegerField(blank=True, default=0, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('countries', models.CharField(blank=True, max_length=255, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=255, null=True)),
                ('backdrop_path', models.CharField(blank=True, max_length=255, null=True)),
                ('original_language', models.CharField(blank=True, max_length=10, null=True)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('vote_count', models.PositiveIntegerField(blank=True, null=True)),
                ('vote_average', models.FloatField(blank=True, null=True)),
                ('budget', models.FloatField(blank=True, default=0, null=True)),
                ('revenue', models.FloatField(blank=True, default=0, null=True)),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
                ('quality', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('source_link', models.CharField(blank=True, max_length=512, null=True)),
                ('generated', models.BooleanField(default=False)),
                ('adult', models.BooleanField(default=False)),
                ('in_production', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('original_title', models.CharField(blank=True, max_length=255, null=True)),
                ('runtime', models.IntegerField(blank=True, default=0, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('countries', models.CharField(blank=True, max_length=255, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=255, null=True)),
                ('backdrop_path', models.CharField(blank=True, max_length=255, null=True)),
                ('original_language', models.CharField(blank=True, max_length=10, null=True)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('vote_count', models.PositiveIntegerField(blank=True, null=True)),
                ('vote_average', models.FloatField(blank=True, null=True)),
                ('number_of_seasons', models.IntegerField(blank=True, default=0, null=True)),
                ('number_of_episodes', models.IntegerField(blank=True, default=0, null=True)),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TmdbApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('site', models.CharField(blank=True, max_length=255, null=True)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='app.movie')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='app.serie')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('source_link', models.CharField(blank=True, max_length=512, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=255, null=True)),
                ('season_number', models.IntegerField(blank=True, default=0, null=True)),
                ('episode_count', models.IntegerField(blank=True, default=0, null=True)),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='app.serie')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embed_link', models.CharField(blank=True, max_length=512, null=True)),
                ('version', models.CharField(blank=True, choices=[('VF', 'VF'), ('VOSTFR', 'VOSTFR')], max_length=255, null=True)),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
                ('episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='app.episode')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='app.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('movies', models.ManyToManyField(blank=True, related_name='genres', to='app.movie')),
                ('series', models.ManyToManyField(blank=True, related_name='genres', to='app.serie')),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='app.season'),
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movies', models.ManyToManyField(blank=True, related_name='directors', to='app.movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.person')),
                ('series', models.ManyToManyField(blank=True, related_name='directors', to='app.serie')),
            ],
        ),
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(blank=True, max_length=255, null=True)),
                ('movies', models.ManyToManyField(blank=True, related_name='casts', to='app.movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='app.person')),
                ('series', models.ManyToManyField(blank=True, related_name='casts', to='app.serie')),
            ],
        ),
    ]
