# Generated by Django 4.2 on 2023-07-06 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_upcomingserie_upcomingmovie_topratedserie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='popularmovie',
            old_name='movie',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='popularserie',
            old_name='reference',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='topratedmovie',
            old_name='reference',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='topratedserie',
            old_name='reference',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='upcomingmovie',
            old_name='reference',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='upcomingserie',
            old_name='reference',
            new_name='source',
        ),
    ]
