# Generated by Django 4.2 on 2023-07-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_movie_popularmovie_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularmovie',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='popularserie',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='topratedmovie',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='topratedserie',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='upcomingmovie',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='upcomingserie',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
