# Generated by Django 4.2 on 2023-07-14 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_comment_visit_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='app.platform'),
        ),
    ]
