# Generated by Django 4.2 on 2023-07-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_popularmovie_enabled_popularserie_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('theme_color', models.CharField(blank=True, default='#4b57fc', max_length=255, null=True)),
                ('background_color', models.CharField(blank=True, default='#111113', max_length=255, null=True)),
                ('dmca', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
