# Generated by Django 4.2 on 2023-07-06 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_platform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platform',
            old_name='short_description',
            new_name='footer_description',
        ),
    ]
