# Generated by Django 4.2 on 2023-07-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='tmdb_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
