# Generated by Django 4.2 on 2023-07-06 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_short_description_platform_footer_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platform',
            old_name='name',
            new_name='domain_name',
        ),
    ]
