# Generated by Django 4.2 on 2023-07-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_name_platform_domain_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='name',
            field=models.CharField(blank=True, default='papystreaming', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='dmca',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='domain_name',
            field=models.CharField(blank=True, default='papystreaming.vip', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='footer_description',
            field=models.TextField(blank=True, default="Qu'est-ce que propose le site série streaming (papystreaming)?<br>le site Web papystreaming Soumettre les Tops Films et Séries, Nouvelles séries, Séries renouvelées,<br>tout ça gratuitement papystreaming est le meilleur site du film et série streaming français.", null=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='keywords',
            field=models.TextField(blank=True, default='film streaming, streaming, film, série streaming, papystreaming, du streaming, streamcomplet, stream complet', null=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='meta_description',
            field=models.TextField(blank=True, default='papystreaming site du films et séries français, Film streaming et série streaming gratuit en vf 2021, Série streaming complet HD fr.', null=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='title',
            field=models.CharField(blank=True, default='papystreaming film streaming et série streaming gratuit', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='url',
            field=models.CharField(blank=True, default='https://wvw.papystreaming.vip/', max_length=255, null=True),
        ),
    ]
