# Generated by Django 4.2 on 2023-07-16 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_request_tmdb_id_alter_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='guests', to='app.user'),
        ),
    ]
