# Generated by Django 4.2 on 2023-07-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_transaction_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='description',
            field=models.TextField(blank=True, default='\n        <div class="text-left">\n        <h3 class="text-uppercase">Gagner de l\'argent avec Papystreaming</h3>\n        Chez Papystreaming, nous offrons une expérience de visionnage de films et de séries incroyable tout en vous donnant la possibilité de gagner de l\'argent. Notre plateforme vous permet de profiter de vos contenus préférés tout en participant à des programmes de récompenses exclusifs. Grâce à notre système de points, vous pouvez accumuler des récompenses en regardant des films et des séries, en interagissant avec la communauté et en partageant votre passion pour le cinéma. Rejoignez-nous dès maintenant et profitez de vos divertissements préférés tout en étant récompensé financièrement sur Papystreaming. \n        <br><br>\n        <h3 class="text-uppercase">Voir Serie Streaming gratuit</h3>\n        Une fois une serie en streaming VF gratuit et complet en ligne est diffusée sur la télé ou sur une chaine, nous l\'ajoutons et nous la mettons directement sur notre site de streaming Papystreaming  avec la meilleure qualité possible, à savoir : Full HD HQ QHD ultra HDTV et 4K. Cela dit, nos téléspectateurs peuvent voir serie streaming gratuit VF – VOSTFR en version langue française avec plusieurs qualités comme en 360p, 720p, 1080p, 2K et 4K selon les dispositifs et selon les serveurs d’hébergement. Du coup, que vous ayez un bon débit ou une mauvaise connexion, ça ne changera rien à votre expérience puisque vous pourriez regarder vos séries préférées et toutes les nouvelles séries en streaming complet saisons et épisodes en illimité. Vous pouvez alors débuter le streaming serie que vous voudriez visionner où que vous soyez tout ça gratuitement et sans compte ni inscription et de profiter du streaming complet sur Papystreaming.\n        <br><br>\n        <h3 class="text-uppercase">Series en streaming VF HD complet</h3>\n        Parmi les qualités qui nous différencient des autres sites streaming serie vf gratuit est que le nôtre regroupe toutes les meilleures series, top serie de la semaine, listes complètes des dernières series sorties en 2023, stream gratuit des series populaires, les séries tendances de ce week-end, anciennes series et toutes les nouvelles series sorties récemment… le tout est ajouté et mis à jour quotidiennement afin que nos visiteurs trouvent la serie streaming de leur choix et pouvoir regarder gratuitement l’ensemble des saisons et episodes de toutes les séries vf en full hd sur des serveurs rapides et des lecteurs optimisés pour le streaming gratuit sans devoir à payer quoi que ce soit et ce sans publicité ni inscription ni besoin de créer un compte. C’est totalement gratuit diffusion de serie en streaming vf hd en ligne, directement sur Papystreaming votre site de streaming gratuit.\n        </div>\n        ', null=True),
        ),
    ]
